"""add user profile fields

Revision ID: 2557e79f733a
Revises: c0fd52f978c6
Create Date: 2026-05-16 22:13:58.494644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2557e79f733a'
down_revision: Union[str, Sequence[str], None] = 'c0fd52f978c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('style_preference', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'style_preference')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
